services:
  nginx:
    image: nginx:latest
    container_name: nginx-backend
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - .:/var/www/html
    networks:
      - backend-network
      - shared-network
    depends_on:
      - novatraxapi

  novatraxapi:
    build: .
    ports:
      - "9000:9000"
    volumes:
      - ./nginx.conf:/var/www/html/nginx.conf
      - .:/var/www/html
    depends_on:
      - postgres
    networks:
      - backend-network
      - shared-network
    env_file:
      - .env
    develop:
      watch:
        - action: sync
          path: ./src
          target: /var/www/html/src
          ignore:
            - var/
            - vendor/
        - action: rebuild
          path: composer.json

  postgres:
    image: postgres:latest
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend-network
      - shared-network
    env_file:
      - .env

networks:
  backend-network:
  shared-network:
    name: novatrax
    driver: bridge
volumes:
  postgres_data:
